
default: &default
  adapter: postgresql
  encoding: unicode
  username: karthi
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: job_application_api_development

production:
  <<: *default
  database: job_application_api_production
  
